name: trailbase
description: Official client library for TrailBase.
homepage: https://trailbase.io
repository: https://github.com/trailbaseio/trailbase
version: 0.6.0

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  crypto: ^3.0.6
  http: ^1.5.0
  jwt_decoder: ^2.0.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
