[package]
name = "wasm-rust-guest-testfixture"
version = "0.0.0"
authors = ["someone"]
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
base64.workspace = true
serde = { version = "^1.0.203", features = ["derive"] }
serde_json = "^1.0.117"
trailbase-wasm = { workspace = true }
